macro (setup_package_version _packageName)
    if (DEFINED ${_packageName}_VERSION)
        message(STATUS "  Ver: ${${_packageName}_VERSION}")
        string (REGEX MATCHALL "[0-9]+" _versionComponents "${${_packageName}_VERSION}")
        list (LENGTH _versionComponents _len)
        if (${_len} GREATER 0)
            list(GET _versionComponents 0 ${_packageName}_VERSION_MAJOR)
        endif()
        if (${_len} GREATER 1)
            list(GET _versionComponents 1 ${_packageName}_VERSION_MINOR)
        endif()
        if (${_len} GREATER 2)
            list(GET _versionComponents 2 ${_packageName}_VERSION_PATCH)
        endif()
        if (${_len} GREATER 3)
            list(GET _versionComponents 3 ${_packageName}_VERSION_TWEAK)
        endif()
        set (${_packageName}_VERSION_COUNT ${_len})
        if (NOT DEFINED ${_packageName}_VERSION_PATCH)
            set(${_packageName}_VERSION_PATCH 0)
        endif()
        if (NOT DEFINED ${_packageName}_VERSION_MINOR)
            set(${_packageName}_VERSION_MINOR 0)
        endif()
        if (NOT DEFINED ${_packageName}_VERSION_MAJOR)
            set(${_packageName}_VERSION_MAJOR 0)
        endif()
        #message(STATUS "    ${${_packageName}_VERSION_MAJOR}")
        #message(STATUS "    ${${_packageName}_VERSION_MINOR}")
        #message(STATUS "    ${${_packageName}_VERSION_PATCH}")
        #mark_as_advanced(FORCE ${_packageName}_VERSION_MAJOR ${_packageName}_VERSION_MINOR ${_packageName}_VERSION_PATCH ${_packageName}_VERSION_COUNT)
        if (${_packageName}_VERSION_TWEAK)
            #mark_as_advanced(FORCE ${_packageName}_VERSION_TWEAK)
        endif()
    else()
        #set (${_packageName}_VERSION_COUNT 0)
        #set (${_packageName}_VERSION "")
    endif()
endmacro()