name: build documentation

on:
  push:
    branches:
      - master

jobs:
  doxygen:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run: sudo apt-get install doxygen graphviz
    - name: generate docs
      run: doxygen
    - name: Deploy docs to gh-pages
      uses: s0/git-publish-subdir-action@master
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: doc/html
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
